/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cjoakim.cosmos;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

    // Class variables
    private static Logger logger = LogManager.getLogger(App.class);



    public static void main(String[] args) {

        if (args.length < 1) {
            logger.error("No command-line args; terminating...");
        }
        else {
            try {
                AppConfig.setCommandLineArgs(args);
                String function = args[0];
                String dbName = null;
                String containerName = null;
                String pk = null;
                AppConfig.display(false);

                switch (function) {

                    case "display_config":
                        displayAppConfig();
                        break;

                    default:
                        logger.error("unknown main function: " + function);
                }
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private static void displayAppConfig() {

        AppConfig.display(true);
    }
}
