#!/bin/bash
# This script was generated by classpath.py.
# It can be executed to do a "jar -xvf" for each jar in the
# CLASSPATH, so as to produce a list of all dependent classes for analysis.
# Chris Joakim, Microsoft


echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/azure/azure-cosmos/4.8.0/azure-cosmos-4.8.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/azure/azure-cosmos/4.8.0/azure-cosmos-4.8.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/azure/azure-core/1.9.0/azure-core-1.9.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/azure/azure-core/1.9.0/azure-core-1.9.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.2/jackson-datatype-jsr310-2.11.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.2/jackson-datatype-jsr310-2.11.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.2/jackson-dataformat-xml-2.11.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.2/jackson-dataformat-xml-2.11.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.2/jackson-module-jaxb-annotations-2.11.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.2/jackson-module-jaxb-annotations-2.11.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/woodstox/woodstox-core/6.2.1/woodstox-core-6.2.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/woodstox/woodstox-core/6.2.1/woodstox-core-6.2.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/projectreactor/reactor-core/3.3.9.RELEASE/reactor-core-3.3.9.RELEASE.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/projectreactor/reactor-core/3.3.9.RELEASE/reactor-core-3.3.9.RELEASE.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.31.Final/netty-tcnative-boringssl-static-2.0.31.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.31.Final/netty-tcnative-boringssl-static-2.0.31.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/azure/azure-core-http-netty/1.6.2/azure-core-http-netty-1.6.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/azure/azure-core-http-netty/1.6.2/azure-core-http-netty-1.6.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-handler-proxy/4.1.51.Final/netty-handler-proxy-4.1.51.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-handler-proxy/4.1.51.Final/netty-handler-proxy-4.1.51.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-common/4.1.51.Final/netty-common-4.1.51.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-common/4.1.51.Final/netty-common-4.1.51.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-buffer/4.1.51.Final/netty-buffer-4.1.51.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-buffer/4.1.51.Final/netty-buffer-4.1.51.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec-http/4.1.51.Final/netty-codec-http-4.1.51.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec-http/4.1.51.Final/netty-codec-http-4.1.51.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec-http2/4.1.51.Final/netty-codec-http2-4.1.51.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec-http2/4.1.51.Final/netty-codec-http2-4.1.51.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.51.Final/netty-transport-native-unix-common-4.1.51.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.51.Final/netty-transport-native-unix-common-4.1.51.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-transport-native-epoll/4.1.51.Final/netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-transport-native-epoll/4.1.51.Final/netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.51.Final/netty-transport-native-kqueue-4.1.51.Final-osx-x86_64.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.51.Final/netty-transport-native-kqueue-4.1.51.Final-osx-x86_64.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/projectreactor/netty/reactor-netty/0.9.11.RELEASE/reactor-netty-0.9.11.RELEASE.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/projectreactor/netty/reactor-netty/0.9.11.RELEASE/reactor-netty-0.9.11.RELEASE.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.11.2/jackson-module-afterburner-2.11.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/module/jackson-module-afterburner/2.11.2/jackson-module-afterburner-2.11.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/dropwizard/metrics/metrics-core/4.1.0/metrics-core-4.1.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/dropwizard/metrics/metrics-core/4.1.0/metrics-core-4.1.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/micrometer/micrometer-core/1.5.5/micrometer-core-1.5.5.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/micrometer/micrometer-core/1.5.5/micrometer-core-1.5.5.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/azure/azure-storage-blob/12.9.0/azure-storage-blob-12.9.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/azure/azure-storage-blob/12.9.0/azure-storage-blob-12.9.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/azure/azure-storage-common/12.9.0/azure-storage-common-12.9.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/azure/azure-storage-common/12.9.0/azure-storage-common-12.9.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/azure/azure-storage-internal-avro/12.0.1/azure-storage-internal-avro-12.0.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/azure/azure-storage-internal-avro/12.0.1/azure-storage-internal-avro-12.0.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/3.5.0/azure-servicebus-3.5.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/3.5.0/azure-servicebus-3.5.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/qpid-proton-j-extensions/1.2.3/qpid-proton-j-extensions-1.2.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/qpid-proton-j-extensions/1.2.3/qpid-proton-j-extensions-1.2.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/asynchttpclient/async-http-client/2.12.1/async-http-client-2.12.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/asynchttpclient/async-http-client/2.12.1/async-http-client-2.12.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/asynchttpclient/async-http-client-netty-utils/2.12.1/async-http-client-netty-utils-2.12.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/asynchttpclient/async-http-client-netty-utils/2.12.1/async-http-client-netty-utils-2.12.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec-socks/4.1.48.Final/netty-codec-socks-4.1.48.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec-socks/4.1.48.Final/netty-codec-socks-4.1.48.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/typesafe/netty/netty-reactive-streams/2.0.4/netty-reactive-streams-2.0.4.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/typesafe/netty/netty-reactive-streams/2.0.4/netty-reactive-streams-2.0.4.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-authentication/1.7.3/azure-client-authentication-1.7.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-authentication/1.7.3/azure-client-authentication-1.7.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-runtime/1.7.3/azure-client-runtime-1.7.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-runtime/1.7.3/azure-client-runtime-1.7.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/rest/client-runtime/1.7.3/client-runtime-1.7.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/rest/client-runtime/1.7.3/client-runtime-1.7.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/retrofit/2.7.2/retrofit-2.7.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/retrofit/2.7.2/retrofit-2.7.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp/3.12.6/okhttp-3.12.6.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp/3.12.6/okhttp-3.12.6.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okio/okio/1.15.0/okio-1.15.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.12.2/logging-interceptor-3.12.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.12.2/logging-interceptor-3.12.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.12.2/okhttp-urlconnection-3.12.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.12.2/okhttp-urlconnection-3.12.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/converter-jackson/2.7.2/converter-jackson-2.7.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/converter-jackson/2.7.2/converter-jackson-2.7.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.10.1/jackson-datatype-joda-2.10.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.10.1/jackson-datatype-joda-2.10.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/reactivex/rxjava/1.3.8/rxjava-1.3.8.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.7.2/adapter-rxjava-2.7.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.7.2/adapter-rxjava-2.7.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.6.4/adal4j-1.6.4.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.6.4/adal4j-1.6.4.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/6.5/oauth2-oidc-sdk-6.5.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/6.5/oauth2-oidc-sdk-6.5.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/mail/javax.mail/1.6.1/javax.mail-1.6.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/mail/javax.mail/1.6.1/javax.mail-1.6.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.5/lang-tag-1.5.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.5/lang-tag-1.5.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-annotations/1.10.0/azure-annotations-1.10.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-annotations/1.10.0/azure-annotations-1.10.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs/3.2.2/azure-eventhubs-3.2.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs/3.2.2/azure-eventhubs-3.2.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/6.0.1/nimbus-jose-jwt-6.0.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/6.0.1/nimbus-jose-jwt-6.0.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.11/commons-lang3-3.11.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.11/commons-lang3-3.11.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.14.0/log4j-slf4j-impl-2.14.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.14.0/log4j-slf4j-impl-2.14.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-core/2.14.0/log4j-core-2.14.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-core/2.14.0/log4j-core-2.14.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.0/log4j-api-2.14.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.0/log4j-api-2.14.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.28/slf4j-simple-1.7.28.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.28/slf4j-simple-1.7.28.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/mongodb/mongo-java-driver/3.12.7/mongo-java-driver-3.12.7.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/mongodb/mongo-java-driver/3.12.7/mongo-java-driver-3.12.7.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tinkerpop/gremlin-driver/3.4.0/gremlin-driver-3.4.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tinkerpop/gremlin-driver/3.4.0/gremlin-driver-3.4.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tinkerpop/gremlin-core/3.4.0/gremlin-core-3.4.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tinkerpop/gremlin-core/3.4.0/gremlin-core-3.4.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tinkerpop/gremlin-shaded/3.4.0/gremlin-shaded-3.4.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tinkerpop/gremlin-shaded/3.4.0/gremlin-shaded-3.4.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/javatuples/javatuples/1.2/javatuples-1.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/javatuples/javatuples/1.2/javatuples-1.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/carrotsearch/hppc/0.7.1/hppc-0.7.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/carrotsearch/hppc/0.7.1/hppc-0.7.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/jcabi/jcabi-manifests/1.1/jcabi-manifests-1.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/jcabi/jcabi-manifests/1.1/jcabi-manifests-1.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/jcabi/jcabi-log/0.14/jcabi-log-0.14.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/jcabi/jcabi-log/0.14/jcabi-log-0.14.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/javapoet/1.8.0/javapoet-1.8.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/javapoet/1.8.0/javapoet-1.8.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/objecthunter/exp4j/0.4.8/exp4j-0.4.8.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/objecthunter/exp4j/0.4.8/exp4j-0.4.8.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/groovy/groovy/2.5.4/groovy-2.5.4-indy.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/groovy/groovy/2.5.4/groovy-2.5.4-indy.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/groovy/groovy-json/2.5.4/groovy-json-2.5.4-indy.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/groovy/groovy-json/2.5.4/groovy-json-2.5.4-indy.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/datastax/cassandra/cassandra-driver-core/3.10.2/cassandra-driver-core-3.10.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/datastax/cassandra/cassandra-driver-core/3.10.2/cassandra-driver-core-3.10.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-handler/4.0.56.Final/netty-handler-4.0.56.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-handler/4.0.56.Final/netty-handler-4.0.56.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-transport/4.0.56.Final/netty-transport-4.0.56.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-transport/4.0.56.Final/netty-transport-4.0.56.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec/4.0.56.Final/netty-codec-4.0.56.Final.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec/4.0.56.Final/netty-codec-4.0.56.Final.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jnr/jnr-ffi/2.1.7/jnr-ffi-2.1.7.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jnr/jnr-ffi/2.1.7/jnr-ffi-2.1.7.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm-commons/5.0.3/asm-commons-5.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jnr/jnr-posix/3.0.44/jnr-posix-3.0.44.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jnr/jnr-posix/3.0.44/jnr-posix-3.0.44.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jnr/jnr-constants/0.9.9/jnr-constants-0.9.9.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jnr/jnr-constants/0.9.9/jnr-constants-0.9.9.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/datastax/cassandra/cassandra-driver-mapping/3.10.2/cassandra-driver-mapping-3.10.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/datastax/cassandra/cassandra-driver-mapping/3.10.2/cassandra-driver-mapping-3.10.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/datastax/cassandra/cassandra-driver-extras/3.10.2/cassandra-driver-extras-3.10.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/datastax/cassandra/cassandra-driver-extras/3.10.2/cassandra-driver-extras-3.10.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/redis/clients/jedis/3.3.0/jedis-3.3.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/redis/clients/jedis/3.3.0/jedis-3.3.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.6.2/commons-pool2-2.6.2.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.6.2/commons-pool2-2.6.2.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.3/jackson-databind-2.11.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.3/jackson-databind-2.11.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.3/jackson-annotations-2.11.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.3/jackson-annotations-2.11.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.3/jackson-core-2.11.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.3/jackson-core-2.11.3.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/activemq/activemq-all/5.16.0/activemq-all-5.16.0.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/activemq/activemq-all/5.16.0/activemq-all-5.16.0.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.33.7/proton-j-0.33.7.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.33.7/proton-j-0.33.7.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar >> tmp/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" >> tmp/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar >> tmp/jar_contents.txt

